version: '3'
services:

  bagh-bandi:
#    build: .
    build:
          context: ..
          dockerfile: ./Dockerfiles/Dockerfile_openai
    ports:
    - "5000:5000"
    stdin_open: true
    tty: true
    network_mode: bridge
    volumes:
     - /Users/quentinvajou/Documents/WorkDev/Python/bagh-bandi:/bagh-bandi
    restart: always
    container_name: open_ai_server
    command: bash

#
#networks:
#  default:
#    external:
#      name: host
